### ISSUE TITLE
1.1.0 release is not working for me

### ISSUE THREAD

**Issue by FabianIsensee** [joblib/threadpoolctl#37] opened 2019-09-16 11:21 UTC
Hi there,
I had major issues on our compute cluster with the newest release of threadpoolctl. I don't quite know what is happening because I don't get any error messages and I have not been able to reproduce the error with a minimalist example. 

What is happening is basically - nothing. I am spawning a bunch of background workers which are supposed to generate data and put it into some queue. The code that runs in the background workers is embedded in `with threadpool_limits(limits=1, user_api="blas"):` to limit the number of threads within each worker. This works perfectly on 1.0.0, but in 1.1.0 no data will arrive in the queue, no error message is printed, cpu is idle (so the really is nothing happening) and I get large core.304403 files in the folder the script was running in (as if there was a segmentation fault).

This issue only occurs on our compute cluster (LSF schedule with modular software stack (maybe this is the problem?), centOS). On my local workstation (Ubuntu 16.04) everything is fine.

I would greatly appreciate if you have any idea why this happens or how this could be resolved.

Best,
Fabian

**Comment by ogrisel** [comment] 2019-09-16 11:29
Can you please report the state of the runtime as detected in both versions of threadpoolctl, both on your local machine and the cluster?

You can use `threadpool_info()` with a minimal script such as:

```python
from pprint import pprint
from threadpoolctl import threadpool_info
import your_modules_with_threadpool

your_modules_with_threadpool.initialize_runtime_or_something()

pprint(threadpool_info())
```

Also can you please provide a minimal reproduction example? You can instrument your script with print statement to identify which line is causing the segfault.

**Comment by ogrisel** [comment] 2019-09-16 11:30
Also, it would be great to try to reproduce the segfault in a docker image with the same version of centos and of your project dependencies.

**Comment by FabianIsensee** [comment] 2019-09-16 11:30
Hi,
just as an update: I am running into this problem on both versions. My previous statement was incorrect. I need to investigate thoroughly but don't have the time right now. I will do this asap and get back to you
Best,
Fabian

**Comment by ogrisel** [comment] 2019-09-18 07:17
Thanks for the updated. We would be really interested in more details to reproduce the issue and be able to fix it. Could you please try to report the BLAS implementation and version?

Do you use Cython with prange loops in your poject? If so please report the compiler version you used to build the Cython code.

Ideally I would like to have the output of a script that reports the state of you runtime on the cluster as said in https://github.com/joblib/threadpoolctl/issues/37#issuecomment-531738451 . You can probably do this using an interactive login on the cluster.

**Comment by FabianIsensee** [comment] 2019-09-18 09:42
Hi there,
I am currently extremely busy and cannot work on it right now. But it is also in my interest to solve this so I will do my best to get you all the information you need asap.
I was using threadpoolctl in our 'batchgenerators' framework (https://github.com/MIC-DKFZ/batchgenerators). Batchgenerators is used to generated batches of training data for deep learning models. It spawns a bunch of background workers that do data augmentation and I need to restrict these background workers to use only 1 thread each. The repo does not use cusotm cython code, but I don't know if any of the packages we use use cython (numpy, scikit-learn, scipy, ...).

Here is what the runtime on our cluster looks like:

> In [2]: from pprint import pprint 
>    ...: from threadpoolctl import threadpool_info 
>    ...: import numpy as np 
>    ...:  
>    ...: pprint(threadpool_info())                                                                           
> [{'filepath': '/home/isensee/dl_venv_new/lib/python3.7/site-packages/numpy/.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so',
>   'internal_api': 'openblas',
>   'num_threads': 1,
>   'prefix': 'libopenblas',
>   'user_api': 'blas',
>   'version': '0.3.7.dev'}]

Note that num_threads is 1 because I set OMP_NUM_THREADS=1 in the environment (this is the workaround I am currently using because threadpoolctl gave problems). 

Interestingly this is the same on my workstation:

> In [1]: from pprint import pprint                                                                                       
> In [2]: from threadpoolctl import threadpool_info                                                                       
> In [3]: import numpy as np                                                                                              
> In [4]: pprint(threadpool_info())                                                                                       
> [{'filepath': '/home/fabian/dl_venv_python3/lib/python3.6/site-packages/numpy/.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so',
>   'internal_api': 'openblas',
>   'num_threads': 1,
>   'prefix': 'libopenblas',
>   'user_api': 'blas',
>   'version': '0.3.7.dev'}]

I will look deeper into this soon and also report a minimal working example that reproduces the problem.
Best,
Fabian

**Comment by FabianIsensee** [comment] 2019-09-18 09:47
Hi,
sorry, my previous threadpool_info was incomplete.

Workstation:

> In [7]: pprint(threadpool_info())                                                                                       
> [{'filepath': '/home/fabian/dl_venv_python3/lib/python3.6/site-packages/numpy/.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so',
>   'internal_api': 'openblas',
>   'num_threads': 1,
>   'prefix': 'libopenblas',
>   'user_api': 'blas',
>   'version': '0.3.7.dev'},
>  {'filepath': '/home/fabian/dl_venv_python3/lib/python3.6/site-packages/scipy/.libs/libopenblasp-r0-39a31c03.2.18.so',
>   'internal_api': 'openblas',
>   'num_threads': 1,
>   'prefix': 'libopenblas',
>   'user_api': 'blas',
>   'version': None},
>  {'filepath': '/home/fabian/dl_venv_python3/lib/python3.6/site-packages/skimage/.libs/libgomp-3300acd3.so.1.0.0',
>   'internal_api': 'openmp',
>   'num_threads': 1,
>   'prefix': 'libgomp',
>   'user_api': 'openmp',
>   'version': None}]


Compute cluster:

> In [8]: pprint(threadpool_info())                                                                           
> [{'filepath': '/home/isensee/dl_venv_new/lib/python3.7/site-packages/numpy/.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so',
>   'internal_api': 'openblas',
>   'num_threads': 1,
>   'prefix': 'libopenblas',
>   'user_api': 'blas',
>   'version': '0.3.7.dev'},
>  {'filepath': '/home/isensee/dl_venv_new/lib/python3.7/site-packages/skimage/.libs/libgomp-3300acd3.so.1.0.0',
>   'internal_api': 'openmp',
>   'num_threads': 1,
>   'prefix': 'libgomp',
>   'user_api': 'openmp',
>   'version': None},
>  {'filepath': '/home/isensee/dl_venv_new/lib/python3.7/site-packages/torch/lib/libgomp-4f651535.so.1',
>   'internal_api': 'openmp',
>   'num_threads': 1,
>   'prefix': 'libgomp',
>   'user_api': 'openmp',
>   'version': None}]

Best,
Fabian

**Comment by ogrisel** [comment] 2019-09-18 09:55
Interesting, it seems that all the runtimes come from either manylinux1 wheel packages (`.libs`) or conda packages (for the libgomp used by torch).

Maybe the issue comes from a bad interaction with fork-based multiprocessing and libgomp and is unrelated to threadpoolctl? But usually this causes a freeze rather than a segfault. In any case you might want to try to use https://github.com/tomMoral/loky instead of multiprocessing to avoid this potential issue (or use the `forkserver` start method of multiprocessing).

I do not understand why you cannot reproduce the issue on your local workstation tough.

**Comment by FabianIsensee** [comment] 2019-09-30 07:23
Hi, apologies for not making it last Friday. There was a deadline on Saturday that I kinda forgot :-D It's very high up my list of priorities right now

**Comment by ogrisel** [comment] 2019-10-07 07:47
Could you please report the output of a `conda list` or `pip freeze` command to see if we can replicate the issue on another machine?

**Comment by FabianIsensee** [comment] 2019-10-10 14:25
(dl_venv_new) -bash-4.2$ pip freeze
apex==0.1
backcall==0.1.0
-e git+ssh://git@phabricator.mitk.org:2222/source/dldabg.git@5fdf8d9fc23230c4dc45e3517cc9d474b19dd2d5#egg=batchgenerators
-e git+https://github.com/FabianIsensee/cifar10.git@1aa58290351dffe86b1ad69eff2e7bed07103dd6#egg=cifar10
-e git+https://github.com/FabianIsensee/cityscapes.git@e9e283c6d58ed797556098991a48f8d351a311b8#egg=cityscapes
cycler==0.10.0
decorator==4.4.0
dicom2nifti==2.1.5
-e git+ssh://git@phabricator.mitk.org:2222/source/isensee.git@8d402fbd6c378f1bc508c0ecaaa7b573223a2e5e#egg=fabians_code
future==0.17.1
graphviz==0.11
-e git+https://github.com/jccurtis/hiddenlayer@0a69f8ade08f2f46f5f1ef4b9fbea93678690839#egg=hiddenlayer
-e git+https://github.com/FabianIsensee/hockey.git@623c16d5d1ca7ac46285240d6261ef3e12e9c204#egg=hockey
imageio==2.5.0
ipython==7.5.0
ipython-genutils==0.2.0
jedi==0.14.0
joblib==0.13.2
kiwisolver==1.1.0
linecache2==1.0.0
matplotlib==3.1.0
-e git+ssh://git@phabricator.mitk.org:2222/source/meddec.git@d89c1dfc39aa51832b97d53970872348cb9a9949#egg=meddec
MedPy==0.4.0
networkx==2.3
nibabel==2.4.1
-e git+ssh://git@phabricator.mitk.org:2222/source/nnunet.git@f52044894edd4540f76003e866590de2471d23d6#egg=nnunet
numpy==1.17.2
pandas==0.24.2
parso==0.5.0
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.0.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pydicom==1.2.2
Pygments==2.4.2
Pympler==0.7
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
-e git+ssh://git@phabricator.mitk.org:2222/source/robustmis.git@985a14fc0fb9418b0625a944ccde3def90c35e34#egg=robustmis&subdirectory=robustmis
scikit-image==0.15.0
scikit-learn==0.21.3
scipy==1.3.1
SimpleITK==1.2.0
six==1.12.0
sklearn==0.0
threadpoolctl==1.1.0
torch==1.3.0.dev20191006
torchvision==0.4.0
tqdm==4.32.2
traceback2==1.4.0
traitlets==4.3.2
unittest2==1.1.0
wcwidth==0.1.7


I have to leave for a conference tomorrow and I need to prepare presentations. That is also what kept me busy these last weeks. Please feel free to ignore this issue until I find the time to get you a proper reproducible example of the problem

**Comment by FabianIsensee** [comment] 2019-10-25 09:05
Hi there,
just to let you know I am working on this right now. Not sure how far I get today. 
So far I have set up a fresh python virtual environment. Running threadpool_info gives the following output:

> [{'filepath': '/home/isensee/thrpctl/lib/python3.7/site-packages/numpy/.libs/libopenblasp-r0-34a18dc3.3.7.so',
>   'internal_api': 'openblas',
>   'num_threads': 1,
>   'prefix': 'libopenblas',
>   'user_api': 'blas',
>   'version': '0.3.7'},
>  {'filepath': '/home/isensee/thrpctl/lib/python3.7/site-packages/skimage/.libs/libgomp-3300acd3.so.1.0.0',
>   'internal_api': 'openmp',
>   'num_threads': 1,
>   'prefix': 'libgomp',
>   'user_api': 'openmp',
>   'version': None},
>  {'filepath': '/home/isensee/thrpctl/lib/python3.7/site-packages/scipy/.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so',
>   'internal_api': 'openblas',
>   'num_threads': 1,
>   'prefix': 'libopenblas',
>   'user_api': 'blas',
>   'version': '0.3.7.dev'},
>  {'filepath': '/home/isensee/thrpctl/lib/python3.7/site-packages/torch/lib/libgomp-7c85b1e2.so.1',
>   'internal_api': 'openmp',
>   'num_threads': 1,
>   'prefix': 'libgomp',
>   'user_api': 'openmp',
>   'version': None}]

pip freeze is the following:

> (thrpctl) -bash-4.2$ pip freeze
> apex==0.1
> -e git+ssh://CUSTOM_URL=batchgenerators
> cycler==0.10.0
> decorator==4.4.0
> dicom2nifti==2.1.7
> -e git+ssh://CUSTOM_URL=fabians_code
> future==0.18.1
> imageio==2.6.1
> joblib==0.14.0
> kiwisolver==1.1.0
> linecache2==1.0.0
> matplotlib==3.1.1
> -e git+ssh://CUSTOM_URL=meddec
> MedPy==0.4.0
> networkx==2.4
> nibabel==2.5.1
> -e git+ssh://CUSTOM_URL=nnunet
> numpy==1.17.3
> pandas==0.25.2
> Pillow==6.2.1
> pydicom==1.3.0
> pyparsing==2.4.2
> python-dateutil==2.8.0
> pytz==2019.3
> PyWavelets==1.1.1
> scikit-image==0.16.2
> scikit-learn==0.21.3
> scipy==1.3.1
> SimpleITK==1.2.3
> six==1.12.0
> sklearn==0.0
> threadpoolctl==1.1.0
> torch==1.3.0
> tqdm==4.36.1
> traceback2==1.4.0
> unittest2==1.1.0


The package that is using threadpoolctl is batchgenerators. In this pip freeze it shows up as private repo, but it is on github as well.

I followed your suggestion to use forkserver and that seems to be working. Do you know what that could be the case? From your comment it seems like this would be unrelated to threadpoolctl - but how can it be that it never crashed before?

I will work on a minimalist example right now to better isolate the problem

**Comment by jeremiedbb** [comment] 2019-10-25 09:15
It may be because before your were only invoking OpenMP in child processes whereas now you also invoke OpenMP in the parent process by using threadpoolctl. This is known to cause deadlocks, see [https://stackoverflow.com/questions/49049388/understanding-openmp-shortcomings-regarding-fork](https://stackoverflow.com/questions/49049388/understanding-openmp-shortcomings-regarding-fork)

**Comment by FabianIsensee** [comment] 2019-10-25 10:50
Thank you very much! It seems that I fixed my problem. Instead of running `with threadpool_limits(limits=1, user_api="blas"):` in my background processes I wrap the spawning of processes:

```
            with threadpool_limits(limits=1, user_api="blas"):
                pprint(threadpool_info())
                for i in range(self.num_processes):
                    self._queues.append(Queue(self.num_cached_per_queue))
                    self._processes.append(Process(target=producer, args=(self._queues[i], self.generator, self.transform, i, self.seeds[i], self.abort_event)))
                    self._processes[-1].daemon = True
                    self._processes[-1].start()
```

I will do more testing and get back to you asap

**Comment by jeremiedbb** [comment] 2019-10-25 10:56
Great ! I'd still advise you not to use the fork method of multiprocessing when OpenMP is involved. Even if it works sometimes, it's unsupported and undefined behavior. You'd be better using the `forkserver` start method of multiprocessing or an alternative multiprocessing library.

**Comment by FabianIsensee** [comment] 2019-10-25 13:04
Hi there,
thank you for the suggestion. @ogrisel recommended loky earlier in this thread and I will check it out soon. Right now I needed a quick fix for this issue.
Do you know if OpenMP will give issues with the 'spawn' start method? Windows users will use that over fork.
Best,
Fabian

**Comment by jeremiedbb** [comment] 2019-10-25 13:07
> Do you know if OpenMP will give issues with the 'spawn' start method?

As far as I know it's safe to use OpenMP with the spawn start method

**Comment by ogrisel** [comment] 2019-10-25 14:30
> As far as I know it's safe to use OpenMP with the spawn start method

Yes but then you can no longer use interactively defined functions or classes (defined in the `__main__` module, e.g. in a script or a jupyter kernel session). Loky is basically the spawn method + a callaback to use cloudpickle to support interactive callables + the ability to reuse old worker process to hide some of the cost of spawning and importing modules in worker processes).

**Comment by ogrisel** [comment] 2019-10-25 14:31
I think we can close this issue now.

**Closed by ogrisel** 2019-10-25 14:31 UTC

**Comment by FabianIsensee** [comment] 2019-10-25 14:33
Thanks! I will try it out.
Yes the issue is resolved. Once again thank you for helping me out :-)

**Comment by ogrisel** [comment] 2019-10-25 15:23
Thanks for the follow-up. It's actually interesting to know that the use of threadpoolctl can make that issue more prevalent.
