### ISSUE TITLE
Tests fails on Mac ARM and packages from macports

### ISSUE THREAD

**Issue by nilason** [joblib/threadpoolctl#162] opened 2024-02-02 10:13 UTC
Running the tests in a MacPorts setting, on an Apple ARM machine, the architecture test fails:

```
Executing:  cd "/opt/local/var/macports/build/_Users_nilason_ports_python_py-threadpoolctl/py311-threadpoolctl/work/threadpoolctl-3.2.0" && /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m installer /opt/local/var/macports/build/_Users_nilason_ports_python_py-threadpoolctl/py311-threadpoolctl/work/threadpoolctl-3.2.0-py3-none-any.whl --destdir /opt/local/var/macports/build/_Users_nilason_ports_python_py-threadpoolctl/py311-threadpoolctl/work/destroot 
--->  Testing py311-threadpoolctl
Executing:  cd "/opt/local/var/macports/build/_Users_nilason_ports_python_py-threadpoolctl/py311-threadpoolctl/work/threadpoolctl-3.2.0" && py.test-3.11 -o addopts='' 
========================================================================= test session starts ==========================================================================
platform darwin -- Python 3.11.7, pytest-7.4.3, pluggy-1.3.0
rootdir: /opt/local/var/macports/build/_Users_nilason_ports_python_py-threadpoolctl/py311-threadpoolctl/work/threadpoolctl-3.2.0
plugins: env-1.1.3, cov-4.1.0, xdist-3.3.1, anyio-4.2.0
collected 63 items

tests/test_threadpoolctl.py ....s.sss.ssssssss.ssssss..s..s.......sssssss.sssss..sss...F..s                                                                      [100%]

=============================================================================== FAILURES ===============================================================================
__________________________________________________________________________ test_architecture ___________________________________________________________________________

    def test_architecture():
        expected_openblas_architectures = (
            # XXX: add more as needed by CI or developer laptops
            "armv8",
            "Haswell",
            "Prescott",  # see: https://github.com/xianyi/OpenBLAS/pull/3485
            "SkylakeX",
            "Sandybridge",
            "VORTEX",
            "Zen",
        )
        expected_blis_architectures = (
            # XXX: add more as needed by CI or developer laptops
            "skx",
            "haswell",
        )
        for lib_info in threadpool_info():
            if lib_info["internal_api"] == "openblas":
>               assert lib_info["architecture"] in expected_openblas_architectures
E               AssertionError: assert 'ARMV8' in ('armv8', 'Haswell', 'Prescott', 'SkylakeX', 'Sandybridge', 'VORTEX', ...)

tests/test_threadpoolctl.py:617: AssertionError
======================================================================= short test summary info ========================================================================
FAILED tests/test_threadpoolctl.py::test_architecture - AssertionError: assert 'ARMV8' in ('armv8', 'Haswell', 'Prescott', 'SkylakeX', 'Sandybridge', 'VORTEX', ...)
=============================================================== 1 failed, 26 passed, 36 skipped in 0.44s ===============================================================
Command failed:  cd "/opt/local/var/macports/build/_Users_nilason_ports_python_py-threadpoolctl/py311-threadpoolctl/work/threadpoolctl-3.2.0" && py.test-3.11 -o addopts='' 
Exit code: 1
Error: Failed to test py311-threadpoolctl: command execution failed
```

The following patch make the tests succeed:

```diff
--- tests/test_threadpoolctl.py.orig
+++ tests/test_threadpoolctl.py
@@ -600,6 +600,7 @@
     expected_openblas_architectures = (
         # XXX: add more as needed by CI or developer laptops
         "armv8",
+        "ARMV8",
         "Haswell",
         "Prescott",  # see: https://github.com/xianyi/OpenBLAS/pull/3485
         "SkylakeX",
```

Would that be a proper fix?

**Comment by ogrisel** [comment] 2024-02-06 17:58
Interesting, I cannot reproduce on my M1 mac. Out of curiosity, how did you install numpy / openblas?

- when installing numpy from pip

```
$ python -m threadpoolctl -i numpy
[
  {
    "user_api": "blas",
    "internal_api": "openblas",
    "num_threads": 8,
    "prefix": "libopenblas",
    "filepath": "/Users/ogrisel/miniforge3/envs/tmp/lib/python3.11/site-packages/numpy/.dylibs/libopenblas64_.0.dylib",
    "version": "0.3.23.dev",
    "threading_layer": "pthreads",
    "architecture": "armv8"
  }
]
```

- when installing numpy from conda-forge:

```
$ python -m threadpoolctl -i numpy
[
  {
    "user_api": "blas",
    "internal_api": "openblas",
    "num_threads": 8,
    "prefix": "libopenblas",
    "filepath": "/Users/ogrisel/miniforge3/envs/tmp/lib/libopenblas.0.dylib",
    "version": "0.3.26",
    "threading_layer": "openmp",
    "architecture": "VORTEX"
  },
  {
    "user_api": "openmp",
    "internal_api": "openmp",
    "num_threads": 8,
    "prefix": "libomp",
    "filepath": "/Users/ogrisel/miniforge3/envs/tmp/lib/libomp.dylib",
    "version": null
  }
]
```

**Comment by ogrisel** [comment] 2024-02-06 17:59
Irrespective of this, please feel free to open a PR with your suggested fix.

**Comment by ogrisel** [comment] 2024-02-06 18:01
From your initial report, I suppose you used macports to install numpy and openblas. It's weird that it introduces casing variability but so be it. We might want to make the assertion in the test case-insensitive.

threadpoolctl should probably still report the name with the original casing of the underlying library though, just in case it matters for debugging low-level runtime/packaging problems.

**Comment by nilason** [comment] 2024-02-07 09:13
Yes, I'm working with MacPorts, where I also co-maintain a couple of GIS related ports (MP lingo for packages).

I turns out the command gives the following result:
```bash
 % /opt/local/bin/python3.12 -m threadpoolctl -i numpy
[]
```

I also tried programmatically using examples in the README with the same negative result. What could be the reason to this?

**Comment by nilason** [comment] 2024-02-07 09:48
For what it is worth, MPs OpenBLAS in _not_ built with OpenMP support:

```
cat /opt/local/lib/pkgconfig/openblas.pc
libdir=/opt/local/lib
libsuffix=
includedir=/opt/local/include/openblas

openblas_config=USE_64BITINT= NO_CBLAS= NO_LAPACK= NO_LAPACKE= DYNAMIC_ARCH=OFF DYNAMIC_OLDER=OFF NO_AFFINITY=1 USE_OPENMP= ARMV8 MAX_THREADS=56 
Name: OpenBLAS
Description: OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version
Version: 0.3.25
URL: https://github.com/OpenMathLib/OpenBLAS
Libs:  -L${libdir} -lopenblas${libsuffix} 
Cflags: -I${includedir}
```

According to [Conda recipe](https://github.com/conda-forge/openblas-feedstock/blob/main/recipe/build.sh), the build target for Apple ARM is `VORTEX`, whereas MP use `ARMV8`.

**Comment by jeremiedbb** [comment] 2024-02-07 12:53
>  We might want to make the assertion in the test case-insensitive.

I think so and opened #165

**Comment by jeremiedbb** [comment] 2024-02-07 13:04
> I also tried programmatically using examples in the README with the same negative result. What could be the reason to this?

Hard to tell. Maybe the name of the shared library file doesn't match what we expect or we're not able to find the expected symbols in it. I'd apply this patch before running the command line again to check to check if we're missing the library somehow or if it's just not loaded in the first place.
```diff
diff --git a/threadpoolctl.py b/threadpoolctl.py
index cfebcb5..632f7b8 100644
--- a/threadpoolctl.py
+++ b/threadpoolctl.py
@@ -986,6 +986,7 @@ class ThreadpoolController:
         for i in range(n_dyld):
             filepath = ctypes.string_at(libc._dyld_get_image_name(i))
             filepath = filepath.decode("utf-8")
+            print(filepath)
 
             # Store the library controller if it is supported and selected
             self._make_controller_from_path(filepath)
@@ -1065,7 +1066,7 @@ class ThreadpoolController:
         for controller_class in _ALL_CONTROLLERS:
             # check if filename matches a supported prefix
             prefix = self._check_prefix(filename, controller_class.filename_prefixes)
-
+            print("detected prefix", prefix)
             # filename does not match any of the prefixes of the candidate
             # library. move to next library.
             if prefix is None:
@@ -1102,6 +1103,8 @@ class ThreadpoolController:
                 for func in controller_class.check_symbols
             ):
                 self.lib_controllers.append(lib_controller)
+            else:
+                print("no required symbols")
 
     def _check_prefix(self, library_basename, filename_prefixes):
         """Return the prefix library_basename starts with

```

**Comment by nilason** [comment] 2024-02-07 13:22
The patch results in a number of lines with "detected prefix None".

**Comment by jeremiedbb** [comment] 2024-02-07 13:26
Right, I updated the patch to only show the relevant ones to avoid the noise

**Comment by nilason** [comment] 2024-02-07 13:36
Now we have tree lines of "detected prefix libblas".

**Comment by jeremiedbb** [comment] 2024-02-07 13:44
hum... We explicitely rule out shared libs named libblas (except on windows) because they might not include all the symbols that threadpoolctl needs. We had an issue where openblas came with a libopenblas.so containing all the required symbols and a libblas containing only a subset of symbols making threadpoolctl crash.

It may be time to reconsider supporting libblas on all platforms but I don't know how to avoid the issue I described above.

**Comment by nilason** [comment] 2024-02-07 13:53
Where is this "libblas.dylib" supposed to be? I don't have it in MacPorts directory.

**Comment by jeremiedbb** [comment] 2024-02-07 13:54
you should have the path just above the "detected prefix libblas" lines. Could you paste the full output ?

**Comment by nilason** [comment] 2024-02-07 13:56
> Where is this "libblas.dylib" supposed to be? I don't have it in MacPorts directory.

Or where (in code) is this detected?

**Comment by nilason** [comment] 2024-02-07 13:58
Aha, is comes from system:
`/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib`

**Comment by jeremiedbb** [comment] 2024-02-07 14:09
note that this is not openblas but macos' veclib which we don't support because it doesn't expose an api to control the number of threads which is the purpose of threadpoolctl

**Comment by nilason** [comment] 2024-02-07 14:09
Is this something loaded from threadpoolctl or numpy?

**Comment by jeremiedbb** [comment] 2024-02-07 14:10
the shared lib is first loaded by numpy, then threadpoolctl inspect all loaded libs but doesn't load them itself

**Comment by nilason** [comment] 2024-02-07 14:14
Seem numpy isn't involved in that part. I run with a non-existing module:

```
python3.12 -m threadpoolctl -i xyz     
WARNING: could not import xyz
detected prefix libblas libblas.dylib /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
detected prefix libblas libblas.dylib /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
detected prefix libblas libblas.dylib /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[]
```

**Comment by nilason** [comment] 2024-02-07 14:15
Or do you mean all loaded libs at all?

**Comment by jeremiedbb** [comment] 2024-02-07 14:19
Then it means that python itself is linked against veclib (which is kind if odd). threadpoolctl just inspect the list of shared libs loaded by a python program but won't try to load a lib that is not already loaded by the program.

**Comment by ogrisel** [comment] 2024-02-09 14:01
> note that this is not openblas but macos' veclib which we don't support because it doesn't expose an api to control the number of threads which is the purpose of threadpoolctl

Note that we will support it partially via flexiblas: you won't be able to inspect / set the number of threads but you should be able to see that it's the active backend of flexiblas. See also the related #135.

**Comment by ogrisel** [comment] 2024-02-13 09:06
Since #165 was merged, let's close this issue and open a new issue dedicated to the problem of:

https://github.com/joblib/threadpoolctl/issues/162#issuecomment-1932138190

**Closed by ogrisel** 2024-02-13 09:06 UTC

**Comment by nilason** [comment] 2024-02-13 10:25
Thanks. The MP's Numpy seems to be faulty, I filed a ticket for that in https://trac.macports.org/ticket/69326.

**Comment by chetooo40** [comment] 2024-04-29 14:24
otool -L /Users/ogrisel/mambaforge-disabled/envs/dev/lib/libblas.3.dylib
/Users/ogrisel/mambaforge-disabled/envs/dev/lib/libblas.3.dylib:
        @rpath/libvecLibFort-ng.dylib (compatibility version 0.0.0, current version 0.0.0)
        /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0, reexport)
        @rpath/liblapack-netlib.3.9.0.dylib (compatibility version 0.0.0, current version 0.0.0, reexport)
        @rpath/liblapacke-netlib.3.9.0.dylib (compatibility version 0.0.0, current version 0.0.0, reexport)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
